# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.6
loader_version=0.19.5
fabric_api_version=0.141.6+1.21.11

# Mod
mod_id=jetpackexpanded
mod_version=1.0.0
maven_group=dev.jetpackexpanded
archives_base_name=jetpack-expanded

# Dependencies
energy_version=4.1.0
